# Generated by Django 6.1.1 on 2026-09-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre y apellido del contacto', max_length=120, verbose_name='Nombre Completo')),
                ('telefono', models.CharField(help_text='Número telefónico de contacto (ej: +56 9 1234 5678)', max_length=25, verbose_name='Teléfono')),
                ('correo', models.EmailField(help_text='Dirección de correo electrónico válida', max_length=150, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(help_text='Dirección física o residencia del contacto', max_length=250, verbose_name='Dirección')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['nombre'],
            },
        ),
    ]
